# Generated by Django 3.0.5 on 2020-05-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
